version: '3.8'

services:
  prelogin-api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: prelogin-api
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production